/*
Computer Vision APIs (2024-02-01)

The Computer Vision API provides state-of-the-art algorithms to process images and return information. For example, it can be used to determine if an image contains mature content, or it can be used to find all the people in an image.  It also has other features like categorizing the content of images, and describing an image with complete English sentences.

API version: 2024-02-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package azurecv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DetectedTextBlock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DetectedTextBlock{}

// DetectedTextBlock A detected text block.
type DetectedTextBlock struct {
	// List of text lines in the text block.
	Lines []DetectedTextLine `json:"lines"`
}

type _DetectedTextBlock DetectedTextBlock

// NewDetectedTextBlock instantiates a new DetectedTextBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetectedTextBlock(lines []DetectedTextLine) *DetectedTextBlock {
	this := DetectedTextBlock{}
	this.Lines = lines
	return &this
}

// NewDetectedTextBlockWithDefaults instantiates a new DetectedTextBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetectedTextBlockWithDefaults() *DetectedTextBlock {
	this := DetectedTextBlock{}
	return &this
}

// GetLines returns the Lines field value
func (o *DetectedTextBlock) GetLines() []DetectedTextLine {
	if o == nil {
		var ret []DetectedTextLine
		return ret
	}

	return o.Lines
}

// GetLinesOk returns a tuple with the Lines field value
// and a boolean to check if the value has been set.
func (o *DetectedTextBlock) GetLinesOk() ([]DetectedTextLine, bool) {
	if o == nil {
		return nil, false
	}
	return o.Lines, true
}

// SetLines sets field value
func (o *DetectedTextBlock) SetLines(v []DetectedTextLine) {
	o.Lines = v
}

func (o DetectedTextBlock) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DetectedTextBlock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lines"] = o.Lines
	return toSerialize, nil
}

func (o *DetectedTextBlock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lines",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDetectedTextBlock := _DetectedTextBlock{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDetectedTextBlock)

	if err != nil {
		return err
	}

	*o = DetectedTextBlock(varDetectedTextBlock)

	return err
}

type NullableDetectedTextBlock struct {
	value *DetectedTextBlock
	isSet bool
}

func (v NullableDetectedTextBlock) Get() *DetectedTextBlock {
	return v.value
}

func (v *NullableDetectedTextBlock) Set(val *DetectedTextBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableDetectedTextBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableDetectedTextBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetectedTextBlock(val *DetectedTextBlock) *NullableDetectedTextBlock {
	return &NullableDetectedTextBlock{value: val, isSet: true}
}

func (v NullableDetectedTextBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetectedTextBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


