/*
Computer Vision APIs (2024-02-01)

The Computer Vision API provides state-of-the-art algorithms to process images and return information. For example, it can be used to determine if an image contains mature content, or it can be used to find all the people in an image.  It also has other features like categorizing the content of images, and describing an image with complete English sentences.

API version: 2024-02-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package azurecv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContentTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentTag{}

// ContentTag An entity observation in the image, along with the confidence score.
type ContentTag struct {
	// Name of the entity.
	Name string `json:"name"`
	// The level of confidence that the entity was observed. Confidence scores span the range of 0.0 to 1.0 (inclusive), with higher values indicating a higher confidence of a match.
	Confidence float64 `json:"confidence"`
}

type _ContentTag ContentTag

// NewContentTag instantiates a new ContentTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentTag(name string, confidence float64) *ContentTag {
	this := ContentTag{}
	this.Name = name
	this.Confidence = confidence
	return &this
}

// NewContentTagWithDefaults instantiates a new ContentTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentTagWithDefaults() *ContentTag {
	this := ContentTag{}
	return &this
}

// GetName returns the Name field value
func (o *ContentTag) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ContentTag) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ContentTag) SetName(v string) {
	o.Name = v
}

// GetConfidence returns the Confidence field value
func (o *ContentTag) GetConfidence() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value
// and a boolean to check if the value has been set.
func (o *ContentTag) GetConfidenceOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Confidence, true
}

// SetConfidence sets field value
func (o *ContentTag) SetConfidence(v float64) {
	o.Confidence = v
}

func (o ContentTag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["confidence"] = o.Confidence
	return toSerialize, nil
}

func (o *ContentTag) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"confidence",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContentTag := _ContentTag{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContentTag)

	if err != nil {
		return err
	}

	*o = ContentTag(varContentTag)

	return err
}

type NullableContentTag struct {
	value *ContentTag
	isSet bool
}

func (v NullableContentTag) Get() *ContentTag {
	return v.value
}

func (v *NullableContentTag) Set(val *ContentTag) {
	v.value = val
	v.isSet = true
}

func (v NullableContentTag) IsSet() bool {
	return v.isSet
}

func (v *NullableContentTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentTag(val *ContentTag) *NullableContentTag {
	return &NullableContentTag{value: val, isSet: true}
}

func (v NullableContentTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


