/*
Computer Vision APIs (2024-02-01)

The Computer Vision API provides state-of-the-art algorithms to process images and return information. For example, it can be used to determine if an image contains mature content, or it can be used to find all the people in an image.  It also has other features like categorizing the content of images, and describing an image with complete English sentences.

API version: 2024-02-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package azurecv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImagePoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImagePoint{}

// ImagePoint An object representing a point in the image.
type ImagePoint struct {
	// The x-coordinate of this point.
	X int32 `json:"x"`
	// The y-coordinate of this point.
	Y int32 `json:"y"`
}

type _ImagePoint ImagePoint

// NewImagePoint instantiates a new ImagePoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImagePoint(x int32, y int32) *ImagePoint {
	this := ImagePoint{}
	this.X = x
	this.Y = y
	return &this
}

// NewImagePointWithDefaults instantiates a new ImagePoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImagePointWithDefaults() *ImagePoint {
	this := ImagePoint{}
	return &this
}

// GetX returns the X field value
func (o *ImagePoint) GetX() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *ImagePoint) GetXOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *ImagePoint) SetX(v int32) {
	o.X = v
}

// GetY returns the Y field value
func (o *ImagePoint) GetY() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *ImagePoint) GetYOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *ImagePoint) SetY(v int32) {
	o.Y = v
}

func (o ImagePoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImagePoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["x"] = o.X
	toSerialize["y"] = o.Y
	return toSerialize, nil
}

func (o *ImagePoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"x",
		"y",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImagePoint := _ImagePoint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImagePoint)

	if err != nil {
		return err
	}

	*o = ImagePoint(varImagePoint)

	return err
}

type NullableImagePoint struct {
	value *ImagePoint
	isSet bool
}

func (v NullableImagePoint) Get() *ImagePoint {
	return v.value
}

func (v *NullableImagePoint) Set(val *ImagePoint) {
	v.value = val
	v.isSet = true
}

func (v NullableImagePoint) IsSet() bool {
	return v.isSet
}

func (v *NullableImagePoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImagePoint(val *ImagePoint) *NullableImagePoint {
	return &NullableImagePoint{value: val, isSet: true}
}

func (v NullableImagePoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImagePoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


