/*
Computer Vision APIs (2024-02-01)

The Computer Vision API provides state-of-the-art algorithms to process images and return information. For example, it can be used to determine if an image contains mature content, or it can be used to find all the people in an image.  It also has other features like categorizing the content of images, and describing an image with complete English sentences.

API version: 2024-02-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package azurecv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DenseCaption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DenseCaption{}

// DenseCaption A brief description of what the image depicts.
type DenseCaption struct {
	// The text of the caption.
	Text string `json:"text"`
	// The level of confidence the service has in the caption. Confidence scores span the range of 0.0 to 1.0 (inclusive), with higher values indicating a higher confidence of a match.
	Confidence float64 `json:"confidence"`
	BoundingBox *BoundingBox `json:"boundingBox,omitempty"`
}

type _DenseCaption DenseCaption

// NewDenseCaption instantiates a new DenseCaption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDenseCaption(text string, confidence float64) *DenseCaption {
	this := DenseCaption{}
	this.Text = text
	this.Confidence = confidence
	return &this
}

// NewDenseCaptionWithDefaults instantiates a new DenseCaption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDenseCaptionWithDefaults() *DenseCaption {
	this := DenseCaption{}
	return &this
}

// GetText returns the Text field value
func (o *DenseCaption) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *DenseCaption) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *DenseCaption) SetText(v string) {
	o.Text = v
}

// GetConfidence returns the Confidence field value
func (o *DenseCaption) GetConfidence() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value
// and a boolean to check if the value has been set.
func (o *DenseCaption) GetConfidenceOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Confidence, true
}

// SetConfidence sets field value
func (o *DenseCaption) SetConfidence(v float64) {
	o.Confidence = v
}

// GetBoundingBox returns the BoundingBox field value if set, zero value otherwise.
func (o *DenseCaption) GetBoundingBox() BoundingBox {
	if o == nil || IsNil(o.BoundingBox) {
		var ret BoundingBox
		return ret
	}
	return *o.BoundingBox
}

// GetBoundingBoxOk returns a tuple with the BoundingBox field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DenseCaption) GetBoundingBoxOk() (*BoundingBox, bool) {
	if o == nil || IsNil(o.BoundingBox) {
		return nil, false
	}
	return o.BoundingBox, true
}

// HasBoundingBox returns a boolean if a field has been set.
func (o *DenseCaption) HasBoundingBox() bool {
	if o != nil && !IsNil(o.BoundingBox) {
		return true
	}

	return false
}

// SetBoundingBox gets a reference to the given BoundingBox and assigns it to the BoundingBox field.
func (o *DenseCaption) SetBoundingBox(v BoundingBox) {
	o.BoundingBox = &v
}

func (o DenseCaption) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DenseCaption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	toSerialize["confidence"] = o.Confidence
	if !IsNil(o.BoundingBox) {
		toSerialize["boundingBox"] = o.BoundingBox
	}
	return toSerialize, nil
}

func (o *DenseCaption) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
		"confidence",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDenseCaption := _DenseCaption{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDenseCaption)

	if err != nil {
		return err
	}

	*o = DenseCaption(varDenseCaption)

	return err
}

type NullableDenseCaption struct {
	value *DenseCaption
	isSet bool
}

func (v NullableDenseCaption) Get() *DenseCaption {
	return v.value
}

func (v *NullableDenseCaption) Set(val *DenseCaption) {
	v.value = val
	v.isSet = true
}

func (v NullableDenseCaption) IsSet() bool {
	return v.isSet
}

func (v *NullableDenseCaption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDenseCaption(val *DenseCaption) *NullableDenseCaption {
	return &NullableDenseCaption{value: val, isSet: true}
}

func (v NullableDenseCaption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDenseCaption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


